- packages/core/src/services/config/IConfigService.ts
- packages/core/src/services/config/defaultConfig.ts
- packages/layout/src/AppControl/index.tsx
- packages/layout/src/AppHeader/index.less
- packages/layout/src/AppHeader/index.tsx
- packages/widgets/src/GridLayer/GridLayerGroup.ts
> feat: hearder 支持设置首页

- lerna.json
- packages/core/package.json
- packages/dipper/package.json
- packages/layout/package.json
- packages/layout/src/hooks/useLayerGroup.ts
- packages/mobile/package.json
- packages/pc/package.json
- packages/widgets/package.json
This reverts commit 361758df2771a14ae99d3100005d76d05ca0cf8c.
> Revert "Revert "feat: 1.修复setSelectFeatures问题""

- .umirc.ts
- README.en-US.md
- README.md
- docs/CNAME
- docs/basis-components/container/base.md
- docs/dev/demo/index.tsx
- docs/mobile/index.md
- docs/pc/components/headerbar.md
- docs/pc/components/map-container.md
- docs/pc/index.md
- 更新文档网站地址为 dipper.antv.vision
- 文档支持别名引用 API 
- 外链常用包，优化文档大小
- 开启 hash
- 优化 SEO 配置meta
> chore: 更新文档网站地址

- docs/basis-api/hooks/useConfigService.md
- docs/basis-api/hooks/useGlobalModel.md
- docs/basis-api/hooks/useLayerGroup.md
- docs/basis-api/hooks/useWidgets.md
- docs/dev/demo/index.tsx
- packages/core/src/services/config/ConfigService.ts
- packages/core/src/services/config/IConfigService.ts
- packages/layout/src/hooks/index.ts
- packages/layout/src/hooks/useConfigService.ts
- packages/layout/src/hooks/useGlobalModel.ts
```tsx
import { useGlobalModel } from '@antv/dipper';
const [globalData, setGlobalData] = useGlobalModel();
setGlobalData({ count: 1 });
// globalData => { count: 1 }
setGlobalData({ add: 1 });
// globalData => { count: 1, add: 1 }
setGlobalData((prevState) => ({ ...prevState, add: prevState.add + 1 }));
// globalData => { count: 1, add: 2 }
```
> feat: 新增 useGlobalModel hook

- packages/core/src/services/config/IConfigService.ts
> fix: 修复接口定义方法名称错误问题

- docs/basis-api/layer/demo/marker-layer/index.tsx
- docs/basis-api/layer/demo/point-layer/color/config/config.ts
- docs/basis-api/layer/demo/point-layer/color/index.tsx
- docs/basis-api/layer/demo/point-layer/hover/config/config.ts
- docs/basis-api/layer/demo/point-layer/hover/index.tsx
- docs/mobile/index.md
- docs/pc/case/demo/task/index.tsx
> docs: 更新点图层 Demo

- docs/basis-api/layer/demo/grid-layer/config/config.ts
- docs/basis-api/layer/demo/image-layer/config/config.ts
- docs/basis-api/layer/demo/layer-group/config/config.ts
- docs/basis-api/layer/demo/marker-layer/config/config.ts
> fix: 修复图层各个demo中的title配置错误问题

- docs/guide/tutorials/index.md
> doc: 修改 useConfigService 引用错误问题

- docs/basis-api/hooks/useLayerGroup.md
- docs/basis-api/layer/demo/marker-layer/widgets/MarkerLayer.tsx
> doc: 修改类型引用路径、删除重复的变量

- packages/core/src/container.ts
- packages/layout/src/hooks/useSceneService.ts
- packages/layout/src/layout/Container/Context.tsx
- packages/layout/src/layout/Layer/index.tsx
- packages/layout/src/layout/Map/index.tsx
- packages/layout/src/widgets/layer/GridLayer/GridLayerGroup.ts
- packages/mobile/src/layout/MapControl/index.tsx
- packages/mobile/src/layout/Panel/index.tsx
- packages/mobile/src/layout/Toolbar/index.tsx
- packages/mobile/src/layout/index.tsx
- packages/pc/src/layout/Container/index.tsx
- packages/pc/src/layout/Header/index.tsx
- packages/pc/src/layout/MapControls/index.tsx
- packages/pc/src/layout/Panel/ToggleButton.tsx
- packages/pc/src/layout/Toolbar/index.tsx
- packages/pc/src/layout/index.ts
- packages/widgets/src/Draw/index.tsx
- packages/widgets/src/Legend/ClassifyColor.tsx
- packages/widgets/src/Legend/MultiClassifyColor.tsx
- packages/widgets/src/Location/index.tsx
- packages/widgets/src/MeshName/index.tsx
- packages/widgets/src/NavBar.tsx
- packages/widgets/src/Search/index.tsx
> fix: lint 错误未使用变量 & mapcontrol 导出问题

- tsconfig.json
> chore: 解决项目多包引入 Definition 问题

- lerna.json
- package.json
```bash
$ yarn run package-version
$ yarn run package-publish
```
> chore: 避免与 npm script hook  冲突修改打包 script

- packages/core/src/container.ts
- packages/layout/src/hooks/useSceneService.ts
- packages/layout/src/layout/Container/Context.tsx
- packages/layout/src/layout/Layer/index.tsx
- packages/layout/src/layout/Map/index.tsx
- packages/layout/src/widgets/layer/GridLayer/GridLayerGroup.ts
- packages/mobile/src/layout/MapControl/index.tsx
- packages/mobile/src/layout/Panel/index.tsx
- packages/mobile/src/layout/Toolbar/index.tsx
- packages/mobile/src/layout/index.tsx
- packages/pc/src/layout/Container/index.tsx
- packages/pc/src/layout/Header/index.tsx
- packages/pc/src/layout/MapControls/index.tsx
- packages/pc/src/layout/Panel/ToggleButton.tsx
- packages/pc/src/layout/Toolbar/index.tsx
- packages/pc/src/layout/index.ts
- packages/widgets/src/Draw/index.tsx
- packages/widgets/src/Legend/ClassifyColor.tsx
- packages/widgets/src/Legend/MultiClassifyColor.tsx
- packages/widgets/src/Location/index.tsx
- packages/widgets/src/MeshName/index.tsx
- packages/widgets/src/NavBar.tsx
- packages/widgets/src/Search/index.tsx
> fix: mapcontrol 导出& 部分 lint warn

- packages/dipper/package.json
- packages/layout/package.json
- packages/mobile/package.json
- packages/pc/package.json
- packages/widgets/package.json
> fix: 修复类型入口文件地址

- docs/guide/quick-start.md
- docs/guide/tutorials/index.md
- packages/mobile/package.json
- packages/pc/package.json
> fix: 修复 peerDependencies 依赖项

- packages/core/src/services/layer/ILayerService.ts
- packages/core/src/services/layer/LayerGroup.ts
- packages/layout/src/widgets/layer/PointLayer/PointLayerGroup.ts
> feat: layergroup 支持 source 配置项

- package.json
- packages/core/package.json
- packages/core/src/services/layer/LayerGroup.ts
- packages/dipper/package.json
- packages/layout/package.json
- packages/mobile/package.json
- packages/pc/package.json
- packages/widgets/package.json
> fix: source option & 添加 tnpm async

- package.json
> chore: 确保 githooks 内置成功

- docs/basis-components/layer/demo/image-layer/widgets/ImageLayer.tsx
- packages/core/src/services/layer/LayerGroup.ts
- packages/layout/src/widgets/layer/ImageLayer/ImageLayerGroup.ts
- packages/layout/src/widgets/layer/PointLayer/PointLayerGroup.ts
- packages/widgets/src/Legend/index.less
- packages/widgets/src/TabsContent/index.tsx
> fix: image layergroup

- .gitignore
- packages/core/.fatherrc.ts
- packages/core/package.json
- packages/dipper/.fatherrc.ts
- packages/dipper/package.json
- packages/layout/.fatherrc.ts
- packages/layout/package.json
- packages/layout/src/widgets/layer/ImageLayer/ImageLayerGroup.ts
- packages/layout/src/widgets/layer/PointLayer/PointLayerGroup.ts
- packages/mobile/.fatherrc.ts
- packages/mobile/package.json
- packages/pc/.fatherrc.ts
- packages/pc/package.json
- packages/widgets/.fatherrc.ts
- packages/widgets/package.json
- packages/widgets/src/Filter/ConfigFilter.tsx
- tsconfig.json
> build: 修复打包问题

- packages/layout/src/layout/Container/Context.tsx
> fix: 修复依赖注入容器复用的情况

- .github/workflows/lint.yml
- .husky/pre-commit
- packages/core/src/services/layer/LayerGroup.ts
- packages/dipper/src/index.ts
- packages/layout/src/layout/Map/index.tsx
- packages/layout/src/widgets/index.ts
- packages/layout/src/widgets/popup/index.tsx
> chore: 给 pre-coomit 添加打包 hook & 修复代码格式问题

- docs/dev/layout/configs/config.ts
- packages/core/package.json
- packages/core/src/services/config/ConfigService.ts
- packages/dipper/package.json
- packages/layout/package.json
- packages/layout/src/hooks/useGlobalModel.ts
- packages/mobile/package.json
- packages/pc/package.json
- packages/widgets/package.json
> fix: 修复 globalmodel 对象引用问题

- docs/basis-api/hooks/useGlobalModel.md
- docs/dev/layout/app.tsx
- docs/dev/layout/configs/config.ts
- packages/layout/src/hooks/useGlobalModel.ts
> fix: 修复 useGlobalModel 类型问题

- docs/dev/layout/configs/config.ts
- docs/dev/layout/index.tsx
- docs/dev/layout/widgets/POILayer.tsx
- docs/dev/layout/widgets/test.tsx
- packages/core/src/services/layer/ILayerService.ts
- packages/core/src/services/layer/LayerService.ts
- packages/layout/src/hooks/useLayerGroup.ts
> fix: uselayergroup hooks

- packages/widgets/src/Filter/CitySelect.tsx
- packages/widgets/src/NavBar.tsx
> fix: 解决 antd 样式全局引入问题

- packages/layout/src/layout/Container/Context.tsx
> fix: 解决更新唯一 Key
